### ISSUE TITLE
Next Step + Back on guidance outside of card

### ISSUE THREAD

**Issue by sugaroverflow** [sugaroverflow/drone-companion-app#198]
The next + back buttons are appearing under the footer on a guidance card ex: `http://localhost:3000/phases/1/tasks/1/steps/3/guidances/`

This is probably because the buttons are setup in `Guidances` instead of on the `GuidanceCard`.

**Comment by xiaoweiguang** [comment]
Moved header and footer from GuidanceList.js to Guidances.js.
